app:
  secret_key: $ENV{APP_SECRET_KEY, random_string}
  database_url: $ENV{DATABASE_URL, postgresql://postgres@localhost/data-engineering-sample-app}
cache:
  host: $ENV{CACHE_HOST, redis://localhost}
  port: $ENV{CACHE_PORT, 6379}
  password: $ENV{CACHE_PWD, }
  ssl: $ENV{CACHE_SSL, True}
access_control:
  hawk_client_id: $ENV{HAWK_CLIENT_ID, client_id}
  hawk_client_key: $ENV{HAWK_CLIENT_KEY, client_key}
  hawk_enabled: $ENV{AC_HAWK_ENABLED, True}
  hawk_nonce_enabled: $ENV{AC_HAWK_NONCE_ENABLED, True}
  hawk_response_header: $ENV{AC_HAWK_RESPONSE_HEADER, True}
  hawk_algorithm: $ENV{AC_HAWK_ALGORITHM, sha256}
  hawk_accept_untrusted_content: $ENV{AC_HAWK_ACCEPT_UNTRUSTED_CONTENT, False}
  hawk_localtime_offset_in_seconds: $ENV{AC_HAWK_LOCALTIME_OFFSET_IN_SECONDS, 0}
  hawk_timestamp_skew_in_seconds: $ENV{AC_HAWK_TIMESTAMP_SKEW_IN_SECONDS, 60}
